// Mocks generated by Mockito 5.3.2 from annotations
// in bloc_quiz_training/test/features/true_false/true_false_block_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bloc_quiz_training/features/true_false_quiz/data_models/true_false_quiz_data_model.dart'
    as _i3;
import 'package:bloc_quiz_training/features/true_false_quiz/repositories/true_false_quiz_repository.dart'
    as _i4;
import 'package:bloc_quiz_training/features/true_false_quiz/services/true_false_quiz_api_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTrueFalseQuizApiServiceImpl_0 extends _i1.SmartFake
    implements _i2.TrueFalseQuizApiServiceImpl {
  _FakeTrueFalseQuizApiServiceImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TrueFalseQuizCopyWith_1<$Res> extends _i1.SmartFake
    implements _i3.$TrueFalseQuizCopyWith<$Res> {
  _Fake$TrueFalseQuizCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TrueFalseQuizRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrueFalseQuizRepositoryImpl extends _i1.Mock
    implements _i4.TrueFalseQuizRepositoryImpl {
  MockTrueFalseQuizRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TrueFalseQuizApiServiceImpl get trueFalseQuizApiService =>
      (super.noSuchMethod(
        Invocation.getter(#trueFalseQuizApiService),
        returnValue: _FakeTrueFalseQuizApiServiceImpl_0(
          this,
          Invocation.getter(#trueFalseQuizApiService),
        ),
      ) as _i2.TrueFalseQuizApiServiceImpl);
  @override
  _i5.Future<List<_i3.TrueFalseQuiz>> fetchOneAnswerQuiz(
          {int? startIndex = 0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOneAnswerQuiz,
          [],
          {#startIndex: startIndex},
        ),
        returnValue:
            _i5.Future<List<_i3.TrueFalseQuiz>>.value(<_i3.TrueFalseQuiz>[]),
      ) as _i5.Future<List<_i3.TrueFalseQuiz>>);
}

/// A class which mocks [TrueFalseQuiz].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrueFalseQuiz extends _i1.Mock implements _i3.TrueFalseQuiz {
  MockTrueFalseQuiz() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.$TrueFalseQuizCopyWith<_i3.TrueFalseQuiz> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$TrueFalseQuizCopyWith_1<_i3.TrueFalseQuiz>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i3.$TrueFalseQuizCopyWith<_i3.TrueFalseQuiz>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
