// Mocks generated by Mockito 5.3.2 from annotations
// in bloc_quiz_training/test/features/one_answer/one_answer_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bloc_quiz_training/features/one_answer_quiz/data_models/one_answer_quiz_data_model.dart'
    as _i3;
import 'package:bloc_quiz_training/features/one_answer_quiz/repositories/one_answer_quiz_repository.dart'
    as _i4;
import 'package:bloc_quiz_training/features/one_answer_quiz/services/one_answer_quiz_api_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOneAnswerQuizApiServiceImpl_0 extends _i1.SmartFake
    implements _i2.OneAnswerQuizApiServiceImpl {
  _FakeOneAnswerQuizApiServiceImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$OneAnswerQuizCopyWith_1<$Res> extends _i1.SmartFake
    implements _i3.$OneAnswerQuizCopyWith<$Res> {
  _Fake$OneAnswerQuizCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OneAnswerQuizRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockOneAnswerQuizRepositoryImpl extends _i1.Mock
    implements _i4.OneAnswerQuizRepositoryImpl {
  MockOneAnswerQuizRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OneAnswerQuizApiServiceImpl get oneAnswerQuizApiService =>
      (super.noSuchMethod(
        Invocation.getter(#oneAnswerQuizApiService),
        returnValue: _FakeOneAnswerQuizApiServiceImpl_0(
          this,
          Invocation.getter(#oneAnswerQuizApiService),
        ),
      ) as _i2.OneAnswerQuizApiServiceImpl);
  @override
  _i5.Future<List<_i3.OneAnswerQuiz>> fetchOneAnswerQuiz(
          {int? startIndex = 0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOneAnswerQuiz,
          [],
          {#startIndex: startIndex},
        ),
        returnValue:
            _i5.Future<List<_i3.OneAnswerQuiz>>.value(<_i3.OneAnswerQuiz>[]),
      ) as _i5.Future<List<_i3.OneAnswerQuiz>>);
}

/// A class which mocks [OneAnswerQuiz].
///
/// See the documentation for Mockito's code generation for more information.
class MockOneAnswerQuiz extends _i1.Mock implements _i3.OneAnswerQuiz {
  MockOneAnswerQuiz() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.$OneAnswerQuizCopyWith<_i3.OneAnswerQuiz> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$OneAnswerQuizCopyWith_1<_i3.OneAnswerQuiz>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i3.$OneAnswerQuizCopyWith<_i3.OneAnswerQuiz>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
